import { useState } from 'react';
import { Card, Badge } from '@/components/ui';
import type { ConsultationDocument } from '@/lib/documents';
import { getDocumentUrl } from '@/lib/documents';
import { FileText, Eye, Download, FileCog } from 'lucide-react';

export function Documents({ documents }: { documents: ConsultationDocument[] }) {
  const [viewing, setViewing] = useState<ConsultationDocument | null>(null);

  if (documents.length === 0) {
    return (
      <div className="animate-fade-in">
        <div className="flex items-center gap-3 mb-6">
          <div className="grid place-items-center h-10 w-10 rounded-xl bg-teal-50 text-teal-600">
            <FileText size={18} />
          </div>
          <div>
            <h1 className="font-display text-xl sm:text-2xl font-bold text-ink-900">Documents</h1>
            <p className="text-sm text-ink-500">Consultation reports and medical documents</p>
          </div>
        </div>
        <Card>
          <div className="py-12 text-center">
            <FileCog size={36} className="mx-auto text-ink-300" />
            <p className="text-sm font-semibold text-ink-500 mt-3">No documents yet</p>
            <p className="text-xs text-ink-400 mt-1">
              Consultation reports generated by your doctor will appear here.
            </p>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="animate-fade-in">
      <div className="flex items-center gap-3 mb-6">
        <div className="grid place-items-center h-10 w-10 rounded-xl bg-teal-50 text-teal-600">
          <FileText size={18} />
        </div>
        <div>
          <h1 className="font-display text-xl sm:text-2xl font-bold text-ink-900">Documents</h1>
          <p className="text-sm text-ink-500">Consultation reports and medical documents</p>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {documents.map((doc) => (
          <Card key={doc.id} hover className="p-5">
            <div className="flex items-start gap-3">
              <div className="grid place-items-center h-11 w-11 rounded-xl bg-red-50 text-red-500 shrink-0">
                <FileText size={20} />
              </div>
              <div className="min-w-0 flex-1">
                <h3 className="font-display font-bold text-ink-900 truncate" title={doc.fileName}>
                  {doc.fileName.replace(/\.pdf$/, '')}
                </h3>
                <div className="flex items-center gap-2 mt-1">
                  <Badge tone="teal">PDF</Badge>
                  <span className="text-xs text-ink-400">
                    {doc.consultationDate || 'Date N/A'}
                  </span>
                </div>
                {doc.doctor && (
                  <p className="text-xs text-ink-400 mt-1">Dr. {doc.doctor}</p>
                )}
              </div>
            </div>
            <div className="flex gap-2 mt-4 pt-3 border-t border-ink-100">
              <button
                onClick={() => setViewing(doc)}
                className="btn-secondary flex-1 px-3 py-2 text-sm"
              >
                <Eye size={15} /> View
              </button>
              <a
                href={getDocumentUrl(doc.filePath)}
                download={doc.fileName}
                className="btn-primary flex-1 px-3 py-2 text-sm"
              >
                <Download size={15} /> Download
              </a>
            </div>
          </Card>
        ))}
      </div>

      {viewing && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink-900/60 backdrop-blur-sm animate-fade-in-fast"
          onClick={() => setViewing(null)}
        >
          <div
            className="relative w-full max-w-4xl h-[90vh] bg-white rounded-2xl shadow-card-hover overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-5 py-3 border-b border-ink-100">
              <div className="flex items-center gap-2 min-w-0">
                <FileText size={18} className="text-red-500 shrink-0" />
                <span className="text-sm font-semibold text-ink-800 truncate">{viewing.fileName}</span>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <a
                  href={getDocumentUrl(viewing.filePath)}
                  download={viewing.fileName}
                  className="btn-primary px-3 py-1.5 text-sm"
                >
                  <Download size={14} /> Download
                </a>
                <button
                  onClick={() => setViewing(null)}
                  className="btn-secondary px-3 py-1.5 text-sm"
                >
                  Close
                </button>
              </div>
            </div>
            <iframe
              src={getDocumentUrl(viewing.filePath)}
              title={viewing.fileName}
              className="flex-1 w-full border-0"
            />
          </div>
        </div>
      )}
    </div>
  );
}
