/*
# Create patients and medical record tables for MED-ID

1. Purpose
Store patient profiles and their full medical records (allergies, conditions,
medications, surgeries, tests) in Supabase so newly registered patients persist
across refreshes and are searchable from the Doctor Portal. The existing
`consultations` table is reused — it already has a `patient_med_id` column.

2. New Tables
- `patients` — one row per patient, keyed by `med_id` (e.g. "MED-102948")
  - `med_id` text PRIMARY KEY
  - `name`, `dob`, `age`, `gender`, `blood_group`, `phone`, `email`, `address`
  - `emergency_contact_name`, `emergency_contact_relation`, `emergency_contact_phone`
  - `emergency_info` — other important emergency info collected at registration
  - `aadhaar` — demo-only 12-digit fictional number, never displayed on dashboard/emergency
  - `created_at` timestamptz
- `patient_allergies` — allergy records linked to a patient
- `patient_conditions` — medical conditions linked to a patient
- `patient_medications` — medication records linked to a patient
- `patient_surgeries` — surgery records linked to a patient
- `patient_tests` — test/investigation records linked to a patient

3. Security
- RLS enabled on every new table.
- Single-tenant demo app (no Supabase auth sign-in screen) → all policies
  use `TO anon, authenticated` with `USING (true)` / `WITH CHECK (true)`
  so the anon-key frontend can read and write.

4. Seed Data
- Inserts the existing demo patient MED-102948 (Aarav Mehta) with all
  allergies, conditions, medications, surgeries, and tests from the
  hardcoded `data.ts` file, so the patient portal continues to show
  the same data after migrating to Supabase.

5. Important Notes
- The `aadhaar` column stores a fictional 12-digit number for the demo.
  It is never used as the MED-ID and is never displayed on the patient
  dashboard or emergency profile.
- MED-IDs are generated by the app as `MED-XXXXXX` (6 digits) and checked
  for uniqueness against this table before insert.
- The existing `consultations` table is unchanged — it already links via
  `patient_med_id`.
*/

-- patients
CREATE TABLE IF NOT EXISTS patients (
  med_id text PRIMARY KEY,
  name text NOT NULL,
  dob text NOT NULL,
  age int,
  gender text DEFAULT '',
  blood_group text NOT NULL,
  phone text DEFAULT '',
  email text DEFAULT '',
  address text DEFAULT '',
  emergency_contact_name text DEFAULT '',
  emergency_contact_relation text DEFAULT '',
  emergency_contact_phone text DEFAULT '',
  emergency_info text DEFAULT '',
  aadhaar text DEFAULT '',
  created_at timestamptz DEFAULT now()
);
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- patient_allergies
CREATE TABLE IF NOT EXISTS patient_allergies (
  id text PRIMARY KEY,
  patient_med_id text NOT NULL,
  name text NOT NULL,
  severity text NOT NULL DEFAULT 'Moderate',
  reaction text DEFAULT ''
);
ALTER TABLE patient_allergies ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_patient_allergies_med ON patient_allergies(patient_med_id);

-- patient_conditions
CREATE TABLE IF NOT EXISTS patient_conditions (
  id text PRIMARY KEY,
  patient_med_id text NOT NULL,
  name text NOT NULL,
  diagnosed_date text DEFAULT '',
  status text NOT NULL DEFAULT 'Active',
  notes text DEFAULT ''
);
ALTER TABLE patient_conditions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_patient_conditions_med ON patient_conditions(patient_med_id);

-- patient_medications
CREATE TABLE IF NOT EXISTS patient_medications (
  id text PRIMARY KEY,
  patient_med_id text NOT NULL,
  name text NOT NULL,
  reason text DEFAULT '',
  prescribed_by text DEFAULT '',
  date text DEFAULT '',
  duration text DEFAULT '',
  status text NOT NULL DEFAULT 'Current',
  dosage text DEFAULT ''
);
ALTER TABLE patient_medications ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_patient_medications_med ON patient_medications(patient_med_id);

-- patient_surgeries
CREATE TABLE IF NOT EXISTS patient_surgeries (
  id text PRIMARY KEY,
  patient_med_id text NOT NULL,
  name text NOT NULL,
  date text DEFAULT '',
  hospital text DEFAULT '',
  surgeon text DEFAULT '',
  outcome text DEFAULT ''
);
ALTER TABLE patient_surgeries ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_patient_surgeries_med ON patient_surgeries(patient_med_id);

-- patient_tests
CREATE TABLE IF NOT EXISTS patient_tests (
  id text PRIMARY KEY,
  patient_med_id text NOT NULL,
  name text NOT NULL,
  date text DEFAULT '',
  type text DEFAULT '',
  result text DEFAULT '',
  status text NOT NULL DEFAULT 'Normal'
);
ALTER TABLE patient_tests ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_patient_tests_med ON patient_tests(patient_med_id);

-- Policies for patients
DROP POLICY IF EXISTS "anon_select_patients" ON patients;
CREATE POLICY "anon_select_patients" ON patients FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_patients" ON patients;
CREATE POLICY "anon_insert_patients" ON patients FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_patients" ON patients;
CREATE POLICY "anon_update_patients" ON patients FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_patients" ON patients;
CREATE POLICY "anon_delete_patients" ON patients FOR DELETE TO anon, authenticated USING (true);

-- Policies for patient_allergies
DROP POLICY IF EXISTS "anon_select_p_allergies" ON patient_allergies;
CREATE POLICY "anon_select_p_allergies" ON patient_allergies FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_p_allergies" ON patient_allergies;
CREATE POLICY "anon_insert_p_allergies" ON patient_allergies FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_p_allergies" ON patient_allergies;
CREATE POLICY "anon_update_p_allergies" ON patient_allergies FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_p_allergies" ON patient_allergies;
CREATE POLICY "anon_delete_p_allergies" ON patient_allergies FOR DELETE TO anon, authenticated USING (true);

-- Policies for patient_conditions
DROP POLICY IF EXISTS "anon_select_p_conditions" ON patient_conditions;
CREATE POLICY "anon_select_p_conditions" ON patient_conditions FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_p_conditions" ON patient_conditions;
CREATE POLICY "anon_insert_p_conditions" ON patient_conditions FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_p_conditions" ON patient_conditions;
CREATE POLICY "anon_update_p_conditions" ON patient_conditions FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_p_conditions" ON patient_conditions;
CREATE POLICY "anon_delete_p_conditions" ON patient_conditions FOR DELETE TO anon, authenticated USING (true);

-- Policies for patient_medications
DROP POLICY IF EXISTS "anon_select_p_medications" ON patient_medications;
CREATE POLICY "anon_select_p_medications" ON patient_medications FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_p_medications" ON patient_medications;
CREATE POLICY "anon_insert_p_medications" ON patient_medications FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_p_medications" ON patient_medications;
CREATE POLICY "anon_update_p_medications" ON patient_medications FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_p_medications" ON patient_medications;
CREATE POLICY "anon_delete_p_medications" ON patient_medications FOR DELETE TO anon, authenticated USING (true);

-- Policies for patient_surgeries
DROP POLICY IF EXISTS "anon_select_p_surgeries" ON patient_surgeries;
CREATE POLICY "anon_select_p_surgeries" ON patient_surgeries FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_p_surgeries" ON patient_surgeries;
CREATE POLICY "anon_insert_p_surgeries" ON patient_surgeries FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_p_surgeries" ON patient_surgeries;
CREATE POLICY "anon_update_p_surgeries" ON patient_surgeries FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_p_surgeries" ON patient_surgeries;
CREATE POLICY "anon_delete_p_surgeries" ON patient_surgeries FOR DELETE TO anon, authenticated USING (true);

-- Policies for patient_tests
DROP POLICY IF EXISTS "anon_select_p_tests" ON patient_tests;
CREATE POLICY "anon_select_p_tests" ON patient_tests FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_p_tests" ON patient_tests;
CREATE POLICY "anon_insert_p_tests" ON patient_tests FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_p_tests" ON patient_tests;
CREATE POLICY "anon_update_p_tests" ON patient_tests FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_p_tests" ON patient_tests;
CREATE POLICY "anon_delete_p_tests" ON patient_tests FOR DELETE TO anon, authenticated USING (true);

-- Seed demo patient MED-102948 (only if not already present)
INSERT INTO patients (med_id, name, dob, age, gender, blood_group, phone, email, address, emergency_contact_name, emergency_contact_relation, emergency_contact_phone)
SELECT 'MED-102948', 'Aarav Mehta', '14 March 1998', 28, 'Male', 'O+', '+91 98200 11234', 'aarav.mehta@example.com', '42, Palm Residency, Bandra West, Mumbai, Maharashtra 400050', 'Neha Mehta', 'Spouse', '+91 98200 44567'
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE med_id = 'MED-102948');

-- Seed allergies (only if table is empty for this patient)
INSERT INTO patient_allergies (id, patient_med_id, name, severity, reaction)
SELECT * FROM (VALUES
  ('a1', 'MED-102948', 'Penicillin', 'Severe', 'Anaphylaxis, hives'),
  ('a2', 'MED-102948', 'Sulfa Drugs', 'Moderate', 'Skin rash'),
  ('a3', 'MED-102948', 'Peanuts', 'Mild', 'Mild itching')
) AS v(id, patient_med_id, name, severity, reaction)
WHERE NOT EXISTS (SELECT 1 FROM patient_allergies WHERE patient_med_id = 'MED-102948' LIMIT 1);

-- Seed conditions
INSERT INTO patient_conditions (id, patient_med_id, name, diagnosed_date, status, notes)
SELECT * FROM (VALUES
  ('c1', 'MED-102948', 'Bronchial Asthma', '12 Jul 2015', 'Managed', 'Controlled with inhaler. Avoids known triggers.'),
  ('c2', 'MED-102948', 'Hypertension (Stage 1)', '02 Feb 2024', 'Active', 'Monitored monthly. Lifestyle modifications advised.'),
  ('c3', 'MED-102948', 'Vitamin D Deficiency', '18 Nov 2023', 'Managed', 'Supplementation ongoing. Levels improving.')
) AS v(id, patient_med_id, name, diagnosed_date, status, notes)
WHERE NOT EXISTS (SELECT 1 FROM patient_conditions WHERE patient_med_id = 'MED-102948' LIMIT 1);

-- Seed medications
INSERT INTO patient_medications (id, patient_med_id, name, reason, prescribed_by, date, duration, status, dosage)
SELECT * FROM (VALUES
  ('m1', 'MED-102948', 'Amlodipine 5mg', 'Hypertension', 'Dr. Priya Sharma', '02 Feb 2024', 'Ongoing', 'Current', 'Once daily, morning'),
  ('m2', 'MED-102948', 'Salbutamol Inhaler', 'Bronchial Asthma', 'Dr. Vikram Rao', '12 Jul 2015', 'As needed', 'Current', '2 puffs as needed'),
  ('m3', 'MED-102948', 'Vitamin D3 60,000 IU', 'Vitamin D Deficiency', 'Dr. Priya Sharma', '18 Nov 2023', '12 weeks', 'Current', 'Once weekly'),
  ('m4', 'MED-102948', 'Amoxicillin 500mg', 'Bacterial infection (fever)', 'Dr. Anil Mehta', '21 Jun 2026', '7 days', 'Completed', 'Three times daily'),
  ('m5', 'MED-102948', 'Ibuprofen 400mg', 'Minor injury pain', 'Dr. Sanjay Gupta', '14 Mar 2026', '5 days', 'Completed', 'As needed, max 3/day'),
  ('m6', 'MED-102948', 'Cetirizine 10mg', 'Skin rash', 'Dr. Kavya Nair', '08 Aug 2026', '10 days', 'Current', 'Once at night'),
  ('m7', 'MED-102948', 'Metformin 500mg', 'Pre-diabetes (preventive)', 'Dr. Priya Sharma', '10 Aug 2023', '6 months', 'Discontinued', 'Twice daily')
) AS v(id, patient_med_id, name, reason, prescribed_by, date, duration, status, dosage)
WHERE NOT EXISTS (SELECT 1 FROM patient_medications WHERE patient_med_id = 'MED-102948' LIMIT 1);

-- Seed surgeries
INSERT INTO patient_surgeries (id, patient_med_id, name, date, hospital, surgeon, outcome)
SELECT * FROM (VALUES
  ('s1', 'MED-102948', 'Appendectomy (Laparoscopic)', '05 May 2022', 'Lilavati Hospital, Mumbai', 'Dr. Rajan Khanna', 'Full recovery, no complications'),
  ('s2', 'MED-102948', 'Tonsillectomy', '22 Oct 2008', 'Hinduja Hospital, Mumbai', 'Dr. S. Nair', 'Full recovery')
) AS v(id, patient_med_id, name, date, hospital, surgeon, outcome)
WHERE NOT EXISTS (SELECT 1 FROM patient_surgeries WHERE patient_med_id = 'MED-102948' LIMIT 1);

-- Seed tests
INSERT INTO patient_tests (id, patient_med_id, name, date, type, result, status)
SELECT * FROM (VALUES
  ('t1', 'MED-102948', 'Complete Blood Count (CBC)', '08 Aug 2026', 'Hematology', 'Within normal range', 'Normal'),
  ('t2', 'MED-102948', 'Lipid Profile', '08 Aug 2026', 'Biochemistry', 'Slightly elevated LDL', 'Abnormal'),
  ('t3', 'MED-102948', 'Chest X-Ray', '21 Jun 2026', 'Radiology', 'Clear, no abnormalities', 'Normal'),
  ('t4', 'MED-102948', 'Vitamin D (25-OH)', '14 Mar 2026', 'Biochemistry', '28 ng/mL (low-normal)', 'Abnormal'),
  ('t5', 'MED-102948', 'HbA1c', '03 Jan 2026', 'Biochemistry', 'Pending', 'Pending')
) AS v(id, patient_med_id, name, date, type, result, status)
WHERE NOT EXISTS (SELECT 1 FROM patient_tests WHERE patient_med_id = 'MED-102948' LIMIT 1);
